name: Update GitHub pages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  page_build:
    name: Update GitHub pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm install --global yarn
    - run: yarn
    - name: Build examples
      run: yarn build-examples
    - name: Copy build
      run: |
        rm -rf /tmp/react-awesome-query-builder
        mkdir /tmp/react-awesome-query-builder
        mkdir /tmp/react-awesome-query-builder/gh-pages
        cp ./packages/examples/build/*bundle* /tmp/react-awesome-query-builder/gh-pages/
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Commit build
      run: |
        cp -R /tmp/react-awesome-query-builder/gh-pages/* .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./*bundle*
        git commit -m "update to ${GITHUB_SHA}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
